server:
  port: 8888
spring:
  datasource:
    username: root
    password: 159629zxc
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.phoenixhell.annotation: debug
