#debug=true #显示开启了哪些配置类
server:
  port: 8999
spring:
  profiles:
    include: prod,test
  banner:
    image:
      location: banner.txt
  mvc:
    static-path-pattern: /static/** #url访问静态资源前缀 影响默认favicon
    hiddenmethod:
      filter:
        enabled: true #开启rest风格 默认为false 仅限于表单,其他比如 postman 等无需此filter 因为表单只能写get和post
    contentnegotiation:
      favor-parameter: true #开启请求参数内容协商模式 设置accept json 还是xml ?format=xml
    servlet:
      path: /  #可以改变 dispatchServlet的默认拦截路径
  resources:
    static-locations: classpath:/static
    add-mappings: false   # false 禁用所有静态资源规则 静态资源放哪都访问不了
    cache:
      period: 11000 # 单位秒 静态资源缓存时间
  servlet:
    multipart:
      max-file-size: 10MB  #文件上传最大限制
      max-request-size: 100MB #所有文件加起来的容量
management:
  endpoints:
    enabled-by-default: true   # 默认true  开启所有监控端点
    web:
      exposure:
        include: '*'             # web发方式暴露  jmx jConsole方式暴露
  endpoint:                      # 显示端点详细信息
    health:
      show-details: always
#/actuator/info
info:
  app_name: spring boot new
  version: 1.0
  mavenProjectName: @project.artifactId@  #使用@ @可以获取maven的pom文件值
  mavenProjectVersion: @project.version@

# 自定义customservice starter
custom:
  hello:
    prefix: hello
    suffix: ----end